import Head from 'next/head'
import { Button } from "@mui/material"
import axios from 'axios'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pakistani Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button variant="text" color="secondary">Text</Button>
    </div>
  )
}


export async function getServerSideProps() {
  try {
    const response = await axios.get(`${process.env.APP_API_URL}/api/profile`)
    return {
      props: {
        status: response.status,
        data: response.data
      },
    }
  } catch (error) {
    console.log(error)
    return {
      props: {
        status: 200,
        data: {
          is_success: false,
          message: 'Something went wrong'
        }
      },
    }
  }
}